// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportInfoManagement.API.Data;

#nullable disable

namespace TransportInfoManagement.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126135133_AddContactsTableOnly")]
    partial class AddContactsTableOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TransportInfoManagement.API.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Tech Street",
                            City = "San Francisco",
                            ClientCode = "CLI001",
                            CompanyName = "Tech Solutions Inc.",
                            ContactPerson = "Robert Chen",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "robert.chen@techsolutions.com",
                            IsActive = true,
                            Phone = "+1-555-1001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Business Ave",
                            City = "New York",
                            ClientCode = "CLI002",
                            CompanyName = "Global Enterprises Ltd.",
                            ContactPerson = "Maria Garcia",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.garcia@globalent.com",
                            IsActive = true,
                            Phone = "+1-555-1002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Innovation Blvd",
                            City = "Seattle",
                            ClientCode = "CLI003",
                            CompanyName = "Digital Innovations Corp.",
                            ContactPerson = "James Wilson",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "james.wilson@digitalinnov.com",
                            IsActive = true,
                            Phone = "+1-555-1003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Service Road",
                            City = "Chicago",
                            ClientCode = "CLI004",
                            CompanyName = "Premier Services Group",
                            ContactPerson = "Sarah Thompson",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sarah.thompson@premierservices.com",
                            IsActive = true,
                            Phone = "+1-555-1004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 System Drive",
                            City = "Austin",
                            ClientCode = "CLI005",
                            CompanyName = "Advanced Systems Co.",
                            ContactPerson = "Michael Rodriguez",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "michael.rodriguez@advancedsys.com",
                            IsActive = true,
                            Phone = "+1-555-1005"
                        },
                        new
                        {
                            Id = 6,
                            Address = "987 Elite Plaza",
                            City = "Los Angeles",
                            ClientCode = "CLI006",
                            CompanyName = "Elite Business Partners",
                            ContactPerson = "Jennifer Martinez",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jennifer.martinez@elitebiz.com",
                            IsActive = true,
                            Phone = "+1-555-1006"
                        },
                        new
                        {
                            Id = 7,
                            Address = "147 Strategy Lane",
                            City = "Boston",
                            ClientCode = "CLI007",
                            CompanyName = "Strategic Solutions LLC",
                            ContactPerson = "David Kim",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.kim@strategicsol.com",
                            IsActive = true,
                            Phone = "+1-555-1007"
                        },
                        new
                        {
                            Id = 8,
                            Address = "258 Prime Street",
                            City = "Denver",
                            ClientCode = "CLI008",
                            CompanyName = "Prime Consulting Group",
                            ContactPerson = "Lisa Anderson",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lisa.anderson@primeconsult.com",
                            IsActive = true,
                            Phone = "+1-555-1008"
                        },
                        new
                        {
                            Id = 9,
                            Address = "369 Modern Way",
                            City = "Portland",
                            ClientCode = "CLI009",
                            CompanyName = "Modern Tech Solutions",
                            ContactPerson = "Christopher Brown",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "christopher.brown@moderntech.com",
                            IsActive = true,
                            Phone = "+1-555-1009"
                        },
                        new
                        {
                            Id = 10,
                            Address = "741 Excellence Blvd",
                            City = "Miami",
                            ClientCode = "CLI010",
                            CompanyName = "Excellence Corporation",
                            ContactPerson = "Amanda White",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "amanda.white@excellencecorp.com",
                            IsActive = true,
                            Phone = "+1-555-1010"
                        },
                        new
                        {
                            Id = 11,
                            Address = "852 Innovation Center",
                            City = "San Diego",
                            ClientCode = "CLI011",
                            CompanyName = "Innovation Hub Inc.",
                            ContactPerson = "Daniel Lee",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "daniel.lee@innovationhub.com",
                            IsActive = true,
                            Phone = "+1-555-1011"
                        },
                        new
                        {
                            Id = 12,
                            Address = "963 Professional Park",
                            City = "Phoenix",
                            ClientCode = "CLI012",
                            CompanyName = "Professional Services Co.",
                            ContactPerson = "Nicole Taylor",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nicole.taylor@profservices.com",
                            IsActive = true,
                            Phone = "+1-555-1012"
                        });
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.ClientService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ClientServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CreatedAt = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            IsActive = true,
                            NumberOfEmployees = 3,
                            ServiceId = 1,
                            StartDate = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            IsActive = true,
                            NumberOfEmployees = 5,
                            ServiceId = 2,
                            StartDate = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            CreatedAt = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 3,
                            EndDate = new DateTime(2023, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            NumberOfEmployees = 2,
                            ServiceId = 3,
                            StartDate = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 4,
                            CreatedAt = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 4,
                            IsActive = true,
                            NumberOfEmployees = 4,
                            ServiceId = 1,
                            StartDate = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 5,
                            CreatedAt = new DateTime(2023, 10, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 5,
                            IsActive = true,
                            NumberOfEmployees = 6,
                            ServiceId = 2,
                            StartDate = new DateTime(2023, 10, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 6,
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 6,
                            IsActive = true,
                            NumberOfEmployees = 3,
                            ServiceId = 3,
                            StartDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 7,
                            CreatedAt = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 7,
                            IsActive = true,
                            NumberOfEmployees = 2,
                            ServiceId = 1,
                            StartDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 8,
                            CreatedAt = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 8,
                            EndDate = new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            NumberOfEmployees = 4,
                            ServiceId = 2,
                            StartDate = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 9,
                            CreatedAt = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 9,
                            IsActive = true,
                            NumberOfEmployees = 5,
                            ServiceId = 3,
                            StartDate = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 10,
                            CreatedAt = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 10,
                            IsActive = true,
                            NumberOfEmployees = 3,
                            ServiceId = 1,
                            StartDate = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            ClientId = 11,
                            CreatedAt = new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 11,
                            IsActive = true,
                            NumberOfEmployees = 4,
                            ServiceId = 2,
                            StartDate = new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            ClientId = 12,
                            CreatedAt = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 12,
                            IsActive = true,
                            NumberOfEmployees = 2,
                            ServiceId = 3,
                            StartDate = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            ClientId = 1,
                            CreatedAt = new DateTime(2023, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            IsActive = true,
                            NumberOfEmployees = 3,
                            ServiceId = 2,
                            StartDate = new DateTime(2023, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            ClientId = 2,
                            CreatedAt = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            IsActive = true,
                            NumberOfEmployees = 4,
                            ServiceId = 1,
                            StartDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            ClientId = 3,
                            CreatedAt = new DateTime(2023, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 4,
                            IsActive = true,
                            NumberOfEmployees = 2,
                            ServiceId = 1,
                            StartDate = new DateTime(2023, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(5094),
                            Description = "Human Resources",
                            IsActive = true,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(5097),
                            Description = "Administration",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(5099),
                            Description = "Service Department",
                            IsActive = true,
                            Name = "Service"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(5100),
                            Description = "Training Department",
                            IsActive = true,
                            Name = "Training"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(5101),
                            Description = "Internet Security Department",
                            IsActive = true,
                            Name = "Internet Security"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(5102),
                            Description = "Auditing Department",
                            IsActive = true,
                            Name = "Auditors"
                        });
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "john.smith@excell-on.com",
                            EmployeeCode = "EMP001",
                            FullName = "John Smith",
                            HireDate = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Phone = "+1-555-0101",
                            Position = "Customer Service Representative",
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "sarah.johnson@excell-on.com",
                            EmployeeCode = "EMP002",
                            FullName = "Sarah Johnson",
                            HireDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Phone = "+1-555-0102",
                            Position = "Sales Manager",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "michael.brown@excell-on.com",
                            EmployeeCode = "EMP003",
                            FullName = "Michael Brown",
                            HireDate = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Phone = "+1-555-0103",
                            Position = "Telemarketing Specialist",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "emily.davis@excell-on.com",
                            EmployeeCode = "EMP004",
                            FullName = "Emily Davis",
                            HireDate = new DateTime(2023, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Phone = "+1-555-0104",
                            Position = "HR Manager",
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "david.wilson@excell-on.com",
                            EmployeeCode = "EMP005",
                            FullName = "David Wilson",
                            HireDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Phone = "+1-555-0105",
                            Position = "Administrative Assistant",
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 4,
                            Email = "jessica.martinez@excell-on.com",
                            EmployeeCode = "EMP006",
                            FullName = "Jessica Martinez",
                            HireDate = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Phone = "+1-555-0106",
                            Position = "Training Coordinator",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 5,
                            Email = "robert.taylor@excell-on.com",
                            EmployeeCode = "EMP007",
                            FullName = "Robert Taylor",
                            HireDate = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Phone = "+1-555-0107",
                            Position = "Security Analyst",
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 6,
                            Email = "lisa.anderson@excell-on.com",
                            EmployeeCode = "EMP008",
                            FullName = "Lisa Anderson",
                            HireDate = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Phone = "+1-555-0108",
                            Position = "Auditor",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "james.thomas@excell-on.com",
                            EmployeeCode = "EMP009",
                            FullName = "James Thomas",
                            HireDate = new DateTime(2023, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Phone = "+1-555-0109",
                            Position = "Customer Support Lead",
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "amanda.white@excell-on.com",
                            EmployeeCode = "EMP010",
                            FullName = "Amanda White",
                            HireDate = new DateTime(2023, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Phone = "+1-555-0110",
                            Position = "Sales Representative",
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "christopher.lee@excell-on.com",
                            EmployeeCode = "EMP011",
                            FullName = "Christopher Lee",
                            HireDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Phone = "+1-555-0111",
                            Position = "Marketing Specialist",
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "michelle.harris@excell-on.com",
                            EmployeeCode = "EMP012",
                            FullName = "Michelle Harris",
                            HireDate = new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Phone = "+1-555-0112",
                            Position = "HR Coordinator",
                            ServiceId = 1
                        });
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(4846),
                            Description = "Receiving calls from customers",
                            IsActive = true,
                            Name = "In-bound Services"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(4853),
                            Description = "Staff proactively calling customers",
                            IsActive = true,
                            Name = "Out-bound Services"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(4854),
                            Description = "Marketing and sales services via telephone",
                            IsActive = true,
                            Name = "Tele Marketing Services"
                        });
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.ServiceFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("FeePerDayPerEmployee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceFees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeePerDayPerEmployee = 4500.00m,
                            ServiceId = 1,
                            UpdatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(5052)
                        },
                        new
                        {
                            Id = 2,
                            FeePerDayPerEmployee = 6000.00m,
                            ServiceId = 2,
                            UpdatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(5057)
                        },
                        new
                        {
                            Id = 3,
                            FeePerDayPerEmployee = 5500.00m,
                            ServiceId = 3,
                            UpdatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(5058)
                        });
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 26, 13, 51, 33, 130, DateTimeKind.Utc).AddTicks(5148),
                            Email = "admin@excell-on.com",
                            FullName = "Administrator",
                            PasswordHash = "$2a$11$T5GEN3lBfOT/6aDBIcejq.npRshOptPonn/aduAjrKYcEx/ZNSu1u",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.ClientService", b =>
                {
                    b.HasOne("TransportInfoManagement.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportInfoManagement.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TransportInfoManagement.API.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.Employee", b =>
                {
                    b.HasOne("TransportInfoManagement.API.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportInfoManagement.API.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.Payment", b =>
                {
                    b.HasOne("TransportInfoManagement.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.Product", b =>
                {
                    b.HasOne("TransportInfoManagement.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TransportInfoManagement.API.Models.ServiceFee", b =>
                {
                    b.HasOne("TransportInfoManagement.API.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
